### PR TITLE
Dead link

### PR DESCRIPTION
**Pull request by M1dgard**
Change link to use an archived version.

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Hi there;

I'm writing this message to let you know that, LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at http://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.

Thanks!

**Comment by ItzLevvie** [comment]
Hi there;

I'm writing this message to let you know that, LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

Thanks!

**Comment by M1dgard** [comment]
Allright. If someone of the maintainers could fix the dead link, that'd be great. :)

CC: @barryclark @zifnab06 (I saw your names in the commit log)

**Comment by ciwrl** [comment]
Thanks for the PR - Gerrit cherry-pick here https://review.lineageos.org/#/c/153988/

**Pull request closed without merging**
